-- SEED RECOVERY: 5 propostas restauradas
INSERT OR REPLACE INTO propostas ("id", "usuario_id", "consultor", "razao_social", "adm_operadora", "modalidade", "tipo_pessoa", "tipo_contrato", "acomodacao", "fator_moderador", "total_vidas", "valor", "vigencia", "regime_aplicado", "num_parcelas", "distribuicao_parcelas", "comissao_total_corretora", "comissao_consultor", "comissao_corretora_liquida", "status", "venda_status", "criado_em", "quem_subiu") VALUES (1, 2, 'Danilo Sampaio', 'GC CALDEIRARIA & SERVICOS LTDA', 'SulAmérica', 'PME PORTE 1', 'PME', 'Adesão', 'Standard', '1.0', 3, 1633.7, '2026-06-19', 'sem_lead_sem_fixo', 4, '1.0;0.6;0.3;0.3', 4574.36, 3594.14, 980.22, 'Ativo', 'Sim', '2026-06-16T21:23:56.000135', 'Reconstrução');
INSERT OR REPLACE INTO propostas ("id", "usuario_id", "consultor", "razao_social", "adm_operadora", "modalidade", "tipo_pessoa", "tipo_contrato", "acomodacao", "fator_moderador", "total_vidas", "valor", "vigencia", "regime_aplicado", "num_parcelas", "distribuicao_parcelas", "comissao_total_corretora", "comissao_consultor", "comissao_corretora_liquida", "status", "venda_status", "criado_em", "quem_subiu") VALUES (2, 3, 'Bianca Sampaio', 'MAURO JUAREZ TULESKI', 'MedSênior', 'PF', 'PF', 'Adesão', 'Standard', '1.0', 1, 1312.78, '2026-06-10', 'sem_lead_sem_fixo', 1, '0.0', 0.0, 0.0, 0.0, 'Ativo', 'Sim', '2026-06-16T21:23:56.005402', 'Reconstrução');
INSERT OR REPLACE INTO propostas ("id", "usuario_id", "consultor", "razao_social", "adm_operadora", "modalidade", "tipo_pessoa", "tipo_contrato", "acomodacao", "fator_moderador", "total_vidas", "valor", "vigencia", "regime_aplicado", "num_parcelas", "distribuicao_parcelas", "comissao_total_corretora", "comissao_consultor", "comissao_corretora_liquida", "status", "venda_status", "criado_em", "quem_subiu") VALUES (3, 3, 'Bianca Sampaio', 'ARLETE KAZUE MORI TULESKI', 'MedSênior', 'PF', 'PF', 'Adesão', 'Standard', '1.0', 1, 1312.78, '2026-06-10', 'sem_lead_sem_fixo', 1, '0.0', 0.0, 0.0, 0.0, 'Ativo', 'Sim', '2026-06-16T21:23:56.006510', 'Reconstrução');
INSERT OR REPLACE INTO propostas ("id", "usuario_id", "consultor", "razao_social", "adm_operadora", "modalidade", "tipo_pessoa", "tipo_contrato", "acomodacao", "fator_moderador", "total_vidas", "valor", "vigencia", "regime_aplicado", "num_parcelas", "distribuicao_parcelas", "comissao_total_corretora", "comissao_consultor", "comissao_corretora_liquida", "status", "venda_status", "criado_em", "quem_subiu") VALUES (4, 2, 'Danilo Sampaio', 'WILLAMI HANDERSON DE OLIVEIRA', 'Amil', 'PME PORTE 1', 'PME', 'Adesão', 'Standard', '1.0', 3, 836.9, '2026-06-12', 'sem_lead_sem_fixo', 4, '1.0;0.6;0.3;0.3', 2343.32, 1841.18, 502.14, 'Ativo', 'Sim', '2026-06-16T21:23:56.007297', 'Reconstrução');
INSERT OR REPLACE INTO propostas ("id", "usuario_id", "consultor", "razao_social", "adm_operadora", "modalidade", "tipo_pessoa", "tipo_contrato", "acomodacao", "fator_moderador", "total_vidas", "valor", "vigencia", "regime_aplicado", "num_parcelas", "distribuicao_parcelas", "comissao_total_corretora", "comissao_consultor", "comissao_corretora_liquida", "status", "venda_status", "criado_em", "quem_subiu") VALUES (5, 2, 'Danilo Sampaio', 'RANIELLY VICTORIA SILVA DE PAIVA', 'Vera Cruz', 'PME PORTE 1', 'PME', 'Adesão', 'Standard', '1.0', 4, 785.37, '2026-06-19', 'sem_lead_sem_fixo', 4, '1.0;0.15;0.08;0.08', 1256.59, 1020.98, 235.61, 'Ativo', 'Sim', '2026-06-16T21:23:56.008350', 'Reconstrução');

-- PARCELAS
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 1, 100.0, 500.0, 0.0, 100.0, NULL, 'Liberado para o corretor', '2026-06', NULL, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 1, 45.45, 1633.7, 2079.25, 45.45, '2026-06-01', 'Pendente de receber', '2026-06', 1, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 2, 27.27, 980.22, 1247.55, 27.27, '2026-07-01', 'Pendente de receber', '2026-07', 2, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 3, 13.64, 490.11, 623.78, 13.64, '2026-08-01', 'Pendente de receber', '2026-08', 3, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 4, 13.64, 490.11, 623.78, 13.64, '2026-09-01', 'Pendente de receber', '2026-09', 4, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (1, 99, 100.0, 150.0, 0.0, 100.0, NULL, 'Liberado para o corretor', '2026-06', NULL, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (2, 1, 100.0, 500.0, 0.0, 100.0, NULL, 'Liberado para o corretor', '2026-06', NULL, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (2, 1, 0.0, 0.0, 0.0, 0.0, '2026-06-01', 'Pendente de receber', '2026-06', 1, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (3, 1, 100.0, 500.0, 0.0, 100.0, NULL, 'Liberado para o corretor', '2026-06', NULL, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (3, 1, 0.0, 0.0, 0.0, 0.0, '2026-06-01', 'Pendente de receber', '2026-06', 1, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (4, 1, 45.45, 836.9, 1065.15, 45.45, '2026-06-01', 'Pendente de receber', '2026-06', 1, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (4, 2, 27.27, 502.14, 639.09, 27.27, '2026-07-01', 'Pendente de receber', '2026-07', 2, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (4, 3, 13.64, 251.07, 319.54, 13.64, '2026-08-01', 'Pendente de receber', '2026-08', 3, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (4, 4, 13.64, 251.07, 319.54, 13.64, '2026-09-01', 'Pendente de receber', '2026-09', 4, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (5, 1, 76.34, 785.37, 959.23, 76.34, '2026-06-01', 'Pendente de receber', '2026-06', 1, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (5, 2, 11.45, 117.81, 143.88, 11.45, '2026-07-01', 'Pendente de receber', '2026-07', 2, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (5, 3, 6.11, 62.83, 76.74, 6.11, '2026-08-01', 'Pendente de receber', '2026-08', 3, 'comissao');
INSERT INTO parcelas ("proposta_id", "numero", "percentual", "valor", "valor_corretora", "perc_cliente", "data_prevista", "status", "competencia", "mensalidade_ref", "tipo_origem") VALUES (5, 4, 6.11, 62.83, 76.74, 6.11, '2026-09-01', 'Pendente de receber', '2026-09', 4, 'comissao');